version: '2.4'
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
    - roberto_pratices_data:/var/lib/mysql

volumes:
  roberto_pratices_data: